name: photoblog example
favicon: null
layout_spectrum: 0.9295499627478421
typography_spectrum: 0.544279056135565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3671533935703337
  lightness: 0.7150180225726217
  saturation: 0.7600873915944248
  rhythmicContrast: 0.5483622145839036
purpose: []
